### ISSUE TITLE
No touch input on jolla C

### ISSUE THREAD

**Issue by szopin** [elros34/sailfish_ubu_chroot#10]
Getting no touch input on jolla C, let me know if any of the logs would help

**Comment by elros34** [comment]
Did you follow the instruction or done something manually? In which apps touch fails? Patched xwayland should fix no touch issue unless it's something else. 
`which Xwayland` should returns /usr/local/bin/Xwayland

**Comment by szopin** [comment]
I first installed on sdcard, no touch on xfce4 or chromium, then tried in home/nemo dir, same. which Xwayland gives:
/usr/bin/Xwayland

**Comment by elros34** [comment]
Location of image doesn't matter, everything is installed in ext4 image unless you are talking about whole project location which must be used on non fat partition.
Enable debugging like explained in README and run this again:
`./ubu-install.sh qxcompositor`

**Comment by szopin** [comment]
Yeah, the initial install might've been on fat, then I tried create in home, but very likely something's left over, how do I purge all leftovers?

**Comment by elros34** [comment]
Everything important is in sailfish_ubu_chroot directory so removing it should be enough.

**Comment by szopin** [comment]
Thanks, redoing everything from scratch fixed it
