### ISSUE TITLE
`p7zip-full` install gives an error

### ISSUE THREAD

**Issue by aerique** [elros34/sailfish_ubu_chroot#16]
Hi, I managed to make the `nemo` user passwords not match after doing `./create.sh` in `sailfish/` and when I ran `create.sh` again it gave a fatal error for the `p7zip-full` install.

It was fixed by adding `--allow-reinstall` to `sfchroot_pkcon install -y p7zip-full` in `common/`.

**Comment by elros34** [comment]
Thanks, looks like in 3.4.0.x pkcon returns 7 exit code when package is already installed.
