### ISSUE TITLE
ubu_create fails trying to read ssh keys

### ISSUE THREAD

**Issue by null-von-sushi** [elros34/sailfish_ubu_chroot#4]
Not sure why, but the ubu_create script fails trying to read SSH keys(?). 
This is a new SFOS installation on Sony XA2. I uploaded the full output when running ubu_create (with debugging on) to a [github gist here](https://gist.github.com/null-von-sushi/0cc5a7ff8619cb9e757f4efd5d584112) in the hopes it may be useful.

**Comment by elros34** [comment]
If you have never used ssh before then file will be missing. Create it via ssh-keygen  as a user without additional password.

**Comment by null-von-sushi** [comment]
I used ssh(fs) to access the device ,and perform actions on the device, however I have not tryied to use the phone as a SSH client before.
After running `ssh-keygen` and accepting the defaults, the script does work.

not sure if it's possible with `devel-su`, but it might be worth checking if the RSA file exists, and if not run `ssh-keygen` as nemo (again, not sure if devel-su allows running commands as specified users).

**Comment by elros34** [comment]
Fixed in audio test branch
